"use client";

import { useEffect, useRef, useState } from "react";
import { tokenize } from "../lib/highlight";
import { Link } from "vocs";
import { WORDMARKS } from "./WalletStrip";

/**
 * Scroll-driven tour of a deployoor project, in the order you add the files.
 *
 * The steps scroll on the left as plain prose; one sticky panel on the right holds a file list that
 * accumulates as you go, with the current file highlighted and its source shown underneath. Files
 * carry a right-aligned `Optional` note where a step is genuinely skippable, so the shape of the
 * project reads straight off the list.
 *
 * Progressive enhancement: prerendered and with JS off, every file in the project is listed and every
 * step's prose is at full contrast — the panel shows the list without a snippet, because step 01 is
 * the project you already have and carries none. Once mounted, the active step is computed from the
 * scroll position, files reveal as you reach them, and the active step's code appears beneath the list.
 */

/**
 * Tools a step can cite, drawn as small logo chips.
 *
 * `icon: true` means a mark is vendored at `/icons/tools/<slug>.svg` (see public/icons/README.md for
 * the viewBox convention). The rest render a monogram in the same chip, so the row looks deliberate
 * until their marks land — add the file, flip the flag, nothing else changes.
 */
type Tool = { readonly label: string; readonly icon?: true };

const TOOLS = {
  hardhat: { label: "Hardhat", icon: true },
  foundry: { label: "Foundry" },
  viem: { label: "viem" },
  wagmi: { label: "wagmi" },
  tevm: { label: "tevm" },
  vitest: { label: "Vitest" },
  jest: { label: "Jest" },
} satisfies Readonly<Record<string, Tool>>;

/** The slugs `leverages` may name, so a typo is a build error rather than a chip that vanishes. */
type ToolSlug = keyof typeof TOOLS;

/** The only flag worth carrying here: whether you need the file at all. */
type Note = "Optional";

type Step = {
  /** Heading prefix; `file` is appended as an inline code chip, matching "Choose your model in …". */
  title: string;
  file: string;
  /** Supports `**bold**` and `` `code` `` — see `renderInline`. */
  blurb: string;
  /** Tools this step leans on, drawn as small logo chips. Keyed to `TOOLS`, so a typo will not build. */
  leverages?: readonly ToolSlug[];
  /** Show the viem-wallet logo row — only the deploy-script step, where the signer is the point. */
  wallets?: boolean;
  /** A "read more" pointer into the docs. */
  link?: { readonly href: string; readonly label: string };
  /** Omitted when the panel should show only the file list (step 1 has no source worth reading). */
  code?: string;
};

type FileRow = {
  path: string;
  /** Step at which the file joins the list. */
  appearsAt: number;
  /** Steps where this row is the highlighted one. Defaults to `[appearsAt]` — spelled out only
   *  when a step adds no file of its own (running the script highlights the script again). */
  activeAt?: readonly number[];
  note?: Note;
};

const ROOT = "my-project/";

/**
 * A step takes over once its top crosses this fraction of the viewport height. Well below the
 * sticky panel's own offset on purpose: a step should activate as soon as its heading is
 * comfortably on screen, not once it has climbed to the very top.
 */
const ACTIVATION_LINE = 0.4;

const STEPS: readonly Step[] = [
  {
    title: "Start with the project you have:",
    file: "hardhat",
    blurb:
      "Contracts in `contracts/`, config in `hardhat.config.js`, and the `artifacts/` that `hardhat compile` writes. **Nothing here changes.** A Foundry project works the same way from `out/`.",
    leverages: ["hardhat", "foundry"],
  },
  {
    title: "Run one command:",
    file: "deployoor generate",
    blurb:
      "It scans your repo and finds your compiled artifacts by reading your **Hardhat or Foundry config**, then writes one typed deployer per contract. Wherever your build output goes, it looks there.",
    code: `# artifacts/ (or out/, or wherever your config points)
npx hardhat compile

# → deployers/, one getOrDeploy per contract
npx deployoor generate`,
  },
  {
    title: "You get a typed deployer per contract in",
    file: "deployers/",
    blurb:
      "Constructor arguments are typed from the abi, so `args` gets checked instead of being a loose array. A deployer holds a name and an abi and nothing else — bytecode and compiler settings are read from your artifacts when you deploy — so these are small enough to **commit and read in a diff**.",
    code: `// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import type { Config } from "deployoor";
import { counterArtifact } from "./types/Counter";

// counterArtifact is a name + abi. The bytecode is read from
// artifacts/ at deploy time, so it is never copied in here.
// Counter's constructor is (uint256), so args is [bigint].
export const getOrDeployCounter = defineDeployer(
  counterArtifact,
  {} satisfies Config,
);`,
  },
  {
    title: "Deploy from a script in",
    file: "scripts/deploy.ts",
    blurb:
      "You pass in the viem clients you already have, so whatever signs for you elsewhere signs for your deploys: a local key, a KMS, an embedded wallet, a hardware wallet. deployoor reaches your wallet through viem alone and **never sees a key**.",
    wallets: true,
    link: { href: "/recipes", label: "Wallet recipes" },
    code: `// The one import that matters: your generated deployer.
import { getOrDeployCounter } from "../deployers";
import { publicClient, walletClient } from "./clients";

// Any viem clients. walletClient signs and needs a chain;
// publicClient reads. Neither is a deployoor type.
const { contract, freshDeploy } = await getOrDeployCounter({
  walletClient,
  publicClient,
  args: [7n], // typed from the constructor
});

// contract is a viem contract: .read.* and .write.* now work.
console.log(await contract.read.number()); // 7n

// true only when this call actually broadcast a deploy tx,
// so one-time setup runs once and not on every run.
if (freshDeploy) await contract.write.increment();`,
  },
  {
    title: "Run it like any other script:",
    file: "tsx scripts/deploy.ts",
    blurb:
      "There is no framework to boot and no task runner, because it is a Node program. The first run deploys and records it. Run it again and you get **the same contract back, with no transaction**.",
    code: `# First run: deploys, then writes the record.
$ npx tsx scripts/deploy.ts
deployed 0x5FbDB2315678afecb367f032d93F642f64180aa3

# Second run: reads the record, sends nothing.
$ npx tsx scripts/deploy.ts
reused 0x5FbDB2315678afecb367f032d93F642f64180aa3`,
  },
  {
    title: "All deployments are recorded in",
    file: "deployments/",
    blurb:
      "One JSON file per contract per chain, with the address, abi, constructor args, tx hash and compiler. Later runs read it to know **the contract already exists**, and `constructorArgs` is how a change to them is something deployoor can notice. `sourcesHash` pins the exact sources it was compiled from, which is what lets `deployoor verify` verify it on an explorer **long after the deploy**.",
    link: { href: "/concepts/deployment-records", label: "Deployment records" },
    code: `deployments/11155111-sepolia/Counter.json

{
  "contractName": "Counter",
  "address": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  "chainId": 11155111,
  "constructorArgs": ["7"],
  "transactionHash": "0x…",
  "sourcesHash": "0x8f3a…"
}`,
  },
  {
    title: "Testing is the same call in",
    file: "test/",
    blurb:
      "The deployer is a plain function over viem clients, so it runs under **any test runner**: Vitest, Jest, `node:test`, or `bun test`. You do not boot a Hardhat or Foundry test environment, and an in-memory EVM means you do not start a node either.",
    leverages: ["vitest", "jest"],
    link: { href: "/guides/testing", label: "Testing guide" },
    code: `import { createTestClients } from "@deployoor/testing";
import { getOrDeployCounter } from "../deployers";

it("deploys with its constructor args", async () => {
  // An in-memory EVM exposed as viem clients, plus an
  // in-memory store, so nothing touches deployments/.
  const { contract } = await getOrDeployCounter({
    ...(await createTestClients()),
    args: [7n],
  });

  // A real deploy on a real EVM, just an in-process one.
  expect(await contract.read.number()).toBe(7n);
});`,
  },
  {
    title: "And you can consume it anywhere, from",
    file: "wagmi.config.ts",
    blurb:
      "Your frontend reads **the same records** your deploy script wrote, through `@wagmi/cli`. Nothing is copied by hand, so an address cannot go stale in one repo while it is correct in the other.",
    leverages: ["wagmi", "viem"],
    link: { href: "/guides/consumption", label: "Consume in your app" },
    code: `import { defineConfig } from "@wagmi/cli";
import { actions } from "@wagmi/cli/plugins";
import { deployments } from "@deployoor/wagmi";

export default defineConfig({
  out: "src/generated.ts",
  plugins: [
    // reads deployments/ — the address and abi come from there
    deployments({ path: "./deployments" }),
    // actions() for viem, react() for hooks
    actions(),
  ],
});`,
  },
  {
    title: "And when you want to change something, there's",
    file: "deployoor.config.ts",
    blurb:
      "Only if you need it — every option has a default, which is why it has not appeared until now. It is where you move folders, and where you add **plugins**: verifiers that publish your source to an explorer, and notifiers that tell your team a deploy happened.",
    link: { href: "/guides/verify", label: "Verify contracts" },
    code: `import { defineConfig } from "deployoor";
import { etherscan } from "@deployoor/etherscan";
import { sourcify } from "@deployoor/sourcify";
import { blockscout } from "@deployoor/blockscout";
import { routescan } from "@deployoor/routescan";
import { slack } from "@deployoor/slack";

export default defineConfig({
  // folders, only if yours are not the defaults
  out: "./generated/deployers",
  deploymentsPath: "./records",

  plugins: [
    // one Etherscan key covers every chain it supports
    etherscan({ apiKey: process.env.ETHERSCAN_API_KEY }),
    // keyless, and not owned by any explorer
    sourcify(),
    // Blockscout runs per chain, so name the instance
    blockscout({ instanceUrl: "https://eth-sepolia.blockscout.com" }),
    // mainnet vs testnet is worked out from the chain id
    routescan(),
    // and tell the team it happened
    slack({ webhook: process.env.SLACK_WEBHOOK }),
  ],
});`,
  },
];

const FILES: readonly FileRow[] = [
  { path: "hardhat.config.js", appearsAt: 0 },
  { path: "contracts/Counter.sol", appearsAt: 0 },
  { path: "artifacts/", appearsAt: 0 },
  // Deliberately one row, not the whole emit. `generate` also writes `deployers/types/<Name>.ts` and
  // an `index.ts` barrel, but this is the first thing a visitor ever reads about deployoor and the
  // file that matters is the deployer. The full tree is in concepts/version-control.
  { path: "deployers/Counter.ts", appearsAt: 1, activeAt: [1, 2] },
  { path: "scripts/deploy.ts", appearsAt: 3, activeAt: [3, 4] },
  { path: "deployments/11155111-sepolia/Counter.json", appearsAt: 5 },
  { path: "test/counter.test.ts", appearsAt: 6, note: "Optional" },
  { path: "wagmi.config.ts", appearsAt: 7, note: "Optional" },
  { path: "deployoor.config.ts", appearsAt: 8, note: "Optional" },
];

const fileState = (file: FileRow, active: number): "active" | "seen" | "ahead" => {
  const activeAt = file.activeAt ?? [file.appearsAt];
  if (activeAt.includes(active)) return "active";
  return file.appearsAt <= active ? "seen" : "ahead";
};

/**
 * Render the sliver of markup the step blurbs use: `**bold**` for the one claim that matters and
 * `` `code` `` for filenames and commands. A full markdown pipeline for two constructs would be
 * more machinery than the copy needs, and keeping it this small is what stops the blurbs from
 * drifting into paragraphs of emphasis.
 */
const renderInline = (text: string) =>
  text.split(/(\*\*[^*]+\*\*|`[^`]+`)/).map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>;
    if (part.startsWith("`") && part.endsWith("`")) return <code key={index}>{part.slice(1, -1)}</code>;
    return part;
  });

const ToolChips = ({ slugs }: { slugs: readonly ToolSlug[] }) => {
  return (
    <div className="anatomy-tools">
      {slugs.map((slug) => {
        // Annotated `Tool` so `icon` is readable across every entry, and indexed by a key of the
        // union so there is no missing-tool case left to drop silently.
        const tool: Tool = TOOLS[slug];
        return (
          <span className="tool-chip" key={slug}>
            {/* Decorative: `.tool-chip-label` below already names the tool in visible text, so
                labelling the mark too (and the wrapper via `title`) announces it three times. */}
            {tool.icon ? (
              <span className="tool-chip-icon" data-tool={slug} aria-hidden="true" />
            ) : (
              <span className="tool-chip-mono" aria-hidden="true">
                {tool.label.slice(0, 1)}
              </span>
            )}
            <span className="tool-chip-label">{tool.label}</span>
          </span>
        );
      })}
    </div>
  );
};

const Code = ({ code }: { code: string }) => {
  return (
    <pre className="anatomy-code">
      <code>
        {tokenize(code).map((token, index) => (
          <span key={index} className={`tok-${token.kind}`}>
            {token.text}
          </span>
        ))}
      </code>
    </pre>
  );
};

export const ProjectAnatomy = () => {
  const [active, setActive] = useState(0);
  const [mounted, setMounted] = useState(false);
  const stepsRef = useRef<(HTMLElement | null)[]>([]);

  useEffect(() => {
    setMounted(true);

    // Derive the active step from the scroll position rather than from IntersectionObserver
    // callbacks. An observer only reports crossings it happens to see, so a fling that carries a
    // step clean past a thin trigger band between two frames leaves the panel showing whatever it
    // showed before — the state can desync from where you actually are, and scrolling back does not
    // necessarily resync it. This is a pure function of geometry, so every scroll event, in either
    // direction, recomputes the same answer from scratch.
    const compute = () => {
      const line = window.innerHeight * ACTIVATION_LINE;
      // Reduced over the raw refs, not a filtered copy: `index` has to be the index into `STEPS`,
      // and filtering first makes it an index into the filtered array. Those coincide only while
      // every step renders, so a step rendered conditionally would silently select the wrong one.
      // The last step whose top has passed the line; index 0 until the first one reaches it.
      setActive(
        stepsRef.current.reduce(
          (found, step, index) => (step !== null && step.getBoundingClientRect().top <= line ? index : found),
          0,
        ),
      );
    };

    // One recompute per frame at most. The flag lives on an object created here, so nothing
    // outside this effect can observe or reassign it.
    const frame = { pending: false };
    const onScroll = () => {
      if (frame.pending) return;
      frame.pending = true;
      requestAnimationFrame(() => {
        frame.pending = false;
        compute();
      });
    };

    compute();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);

    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
  }, []);

  const step = STEPS[active] ?? STEPS[0];

  return (
    <section
      className="anatomy"
      aria-label="Anatomy of a deployoor project"
      data-mounted={mounted ? "true" : "false"}
    >
      <header className="anatomy-head">
        <h2 className="anatomy-title">Anatomy of a deployoor project</h2>
        <p className="anatomy-sub">From the project you already have to a typed, committed deployment.</p>
      </header>

      <div className="anatomy-grid">
        <ol className="anatomy-steps">
          {STEPS.map((entry, index) => (
            <li
              key={entry.file}
              className="anatomy-step"
              data-index={index}
              data-active={index === active ? "true" : "false"}
              ref={(node) => {
                stepsRef.current[index] = node;
              }}
            >
              <span className="anatomy-step-num">{String(index + 1).padStart(2, "0")}</span>
              <h3 className="anatomy-step-title">
                {entry.title} <code>{entry.file}</code>
              </h3>
              <p className="anatomy-step-blurb">{renderInline(entry.blurb)}</p>
              {entry.wallets ? (
                <div className="anatomy-step-wallets">
                  <p className="anatomy-step-wallets-caption">Works with any viem-compatible wallet</p>
                  {/* The .env badge is a filled shape rather than lettering, so as a mask at this
                      size it reads as a blob. The prose already says "a local key". */}
                  {WORDMARKS.filter((wordmark) => wordmark.slug !== "dotenv").map((wordmark) => (
                    <span
                      key={wordmark.slug}
                      className={`wordmark wordmark-${wordmark.slug}`}
                      role="img"
                      aria-label={wordmark.name}
                    />
                  ))}
                </div>
              ) : null}
              {entry.leverages ? <ToolChips slugs={entry.leverages} /> : null}
              {entry.link ? (
                <Link to={entry.link.href} className="anatomy-step-link">
                  {/* The label carries the underline, not the anchor: text-decoration propagates to
                      descendants, so decorating the anchor also underlines the gap and the arrow. */}
                  <span>{entry.link.label}</span>
                </Link>
              ) : null}
              {/* Shown only in the one-column layout, where the panel cannot follow along —
                  Vocs sets overflow-x on its content wrapper below md, which disables sticky. */}
              {entry.code === undefined ? null : (
                <div className="anatomy-step-code">
                  <Code code={entry.code} />
                </div>
              )}
            </li>
          ))}
        </ol>

        <aside className="anatomy-panel">
          <div className="anatomy-files">
            <p className="anatomy-files-root">{ROOT}</p>
            <ul className="anatomy-files-list">
              {FILES.map((file) => (
                <li key={file.path} className="anatomy-file" data-state={fileState(file, active)}>
                  <span className="anatomy-file-path">{file.path}</span>
                  {file.note ? <span className="anatomy-file-note">{file.note}</span> : null}
                </li>
              ))}
            </ul>
          </div>
          {step.code === undefined ? null : <Code code={step.code} />}
        </aside>
      </div>
    </section>
  );
};
