// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import type { Config } from "deployoor";
import { counterArtifact } from "./types/Counter";

export const getOrDeployCounter = defineDeployer(counterArtifact, {} satisfies Config);
