// AUTO-GENERATED by deployoor. Do not edit by hand.
import type { GeneratedArtifact } from "deployoor";

const abi = [{"type":"constructor","inputs":[{"name":"_endpoint","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},{"type":"function","name":"endpoint","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract ILayerZeroEndpoint"}],"stateMutability":"view"},{"type":"function","name":"peers","inputs":[{"name":"eid","type":"uint32","internalType":"uint32"}],"outputs":[{"name":"peer","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},{"type":"function","name":"ping","inputs":[{"name":"_dstEid","type":"uint32","internalType":"uint32"},{"name":"_message","type":"string","internalType":"string"}],"outputs":[],"stateMutability":"payable"},{"type":"function","name":"setPeer","inputs":[{"name":"_eid","type":"uint32","internalType":"uint32"},{"name":"_peer","type":"bytes32","internalType":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"event","name":"PeerSet","inputs":[{"name":"eid","type":"uint32","indexed":true,"internalType":"uint32"},{"name":"peer","type":"bytes32","indexed":false,"internalType":"bytes32"}],"anonymous":false},{"type":"event","name":"PingSent","inputs":[{"name":"dstEid","type":"uint32","indexed":true,"internalType":"uint32"},{"name":"message","type":"string","indexed":false,"internalType":"string"}],"anonymous":false}] as const;

export const pingArtifact = {
  name: "Ping",
  fullyQualifiedName: "src/Ping.sol:Ping",
  abi,
} satisfies GeneratedArtifact<typeof abi>;
