// AUTO-GENERATED by deployoor. Do not edit by hand.
import type { GeneratedArtifact } from "deployoor";

const abi = [{"type":"constructor","inputs":[{"name":"_endpoint","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},{"type":"function","name":"endpoint","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract ILayerZeroEndpoint"}],"stateMutability":"view"},{"type":"function","name":"lastMessage","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"function","name":"lastSrcEid","inputs":[],"outputs":[{"name":"","type":"uint32","internalType":"uint32"}],"stateMutability":"view"},{"type":"function","name":"onPing","inputs":[{"name":"_srcEid","type":"uint32","internalType":"uint32"},{"name":"_message","type":"string","internalType":"string"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"peers","inputs":[{"name":"eid","type":"uint32","internalType":"uint32"}],"outputs":[{"name":"peer","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},{"type":"function","name":"setPeer","inputs":[{"name":"_eid","type":"uint32","internalType":"uint32"},{"name":"_peer","type":"bytes32","internalType":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"event","name":"PeerSet","inputs":[{"name":"eid","type":"uint32","indexed":true,"internalType":"uint32"},{"name":"peer","type":"bytes32","indexed":false,"internalType":"bytes32"}],"anonymous":false},{"type":"event","name":"PongReceived","inputs":[{"name":"srcEid","type":"uint32","indexed":true,"internalType":"uint32"},{"name":"message","type":"string","indexed":false,"internalType":"string"}],"anonymous":false}] as const;

export const pongArtifact = {
  name: "Pong",
  fullyQualifiedName: "src/Pong.sol:Pong",
  abi,
} satisfies GeneratedArtifact<typeof abi>;
