import { describe, it, expect } from "vitest";
import { createTestClients } from "@deployoor/testing";
// Generated by `deployoor generate`, which compiled src/Counter.sol with tevm (see `e2e`).
import { getOrDeployCounter } from "../deployers";

describe("tevm example", () => {
  it("deploys the tevm-compiled Counter to an in-memory EVM — no Hardhat, no Foundry, no disk", async () => {
    // Spreading `clients` passes the in-memory store, so nothing is written to deployments/.
    const clients = await createTestClients();

    const { contract: counter, freshDeploy } = await getOrDeployCounter({ ...clients, args: [7n] });
    expect(freshDeploy).toBe(true);
    expect(counter.address).toMatch(/^0x[0-9a-fA-F]{40}$/);

    expect(await counter.read.number()).toBe(7n);
    await counter.write.increment();
    expect(await counter.read.number()).toBe(8n);
  });
});
