// AUTO-GENERATED by deployoor. Do not edit by hand.
import type { GeneratedArtifact } from "deployoor";

const abi = [{"type":"constructor","inputs":[{"name":"initial","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},{"type":"function","name":"increment","inputs":[],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"number","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"setNumber","inputs":[{"name":"n","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"}] as const;

export const counterArtifact = {
  name: "Counter",
  fullyQualifiedName: "src/Counter.sol:Counter",
  abi,
} satisfies GeneratedArtifact<typeof abi>;
