// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineRegister, defineReset } from "deployoor";
import type { Config } from "deployoor";

export { getOrDeployCounter } from "./Counter";

// Record a contract you did not deploy (e.g. USDC), or forget recorded deployments —
// both config-bound and scoped to the client's chain, like the generated deployers.
export const register = defineRegister({} satisfies Config);
export const reset = defineReset({} satisfies Config);
