// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import type { Config } from "deployoor";
import { pingArtifact } from "./types/Ping";

export const getOrDeployPing = defineDeployer(pingArtifact, {} satisfies Config);
