// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import type { Config } from "deployoor";
import { pongArtifact } from "./types/Pong";

export const getOrDeployPong = defineDeployer(pongArtifact, {} satisfies Config);
