// AUTO-GENERATED by deployoor. Do not edit by hand.
import type { GeneratedArtifact } from "deployoor";

const abi = [{"inputs":[{"internalType":"uint256","name":"initial","type":"uint256"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"increment","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"number","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"n","type":"uint256"}],"name":"setNumber","outputs":[],"stateMutability":"nonpayable","type":"function"}] as const;

export const counterArtifact = {
  name: "Counter",
  fullyQualifiedName: "src/Counter.sol:Counter",
  abi,
} satisfies GeneratedArtifact<typeof abi>;
